# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9079dde69534207527e26206d1401b21762e5c0bc5d3147b5ed8ca0abdc3e84f7bd8de32f51cb50140cf2cdd85ff280c0b2f0f2652c7bf7ab0f0e0cd2c704240

test:
  secret_key_base: 840754003ab6ccbf94dda11ae2178f23a12a06a81d7d1b2b2b8d4664033d1f4ff5732203a1f511cf0a0c54ede3fc7218874ff24c52b117124e28de21694e52c9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
